#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "parser/parser.y".
#

require 'racc/parser'


module N3

  class Parser < Racc::Parser

module_eval <<'..end parser/parser.y modeval..idbbc402f2e7', 'parser/parser.y', 80

  def parse(str)
    @lexer = ::N3::Lexer.new(str)
    do_parse
  end

  def next_token
    token = @lexer.next_token
    p token if $DEBUG
    token
  end

  def on_error(error_token_id, error_value, value_stack)
    puts "Parse Error:"
    p @lexer.current_position
    puts "TOKEN: " + token_to_str(error_token_id)
    puts "VALUE: " + error_value.to_s
    p value_stack
    exit
  end
..end parser/parser.y modeval..idbbc402f2e7

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 3, 38, :_reduce_1,
 1, 38, :_reduce_2,
 2, 39, :_reduce_3,
 2, 39, :_reduce_4,
 3, 39, :_reduce_5,
 1, 37, :_reduce_none,
 2, 41, :_reduce_none,
 2, 41, :_reduce_none,
 2, 43, :_reduce_9,
 3, 45, :_reduce_none,
 3, 45, :_reduce_none,
 1, 45, :_reduce_none,
 3, 47, :_reduce_13,
 1, 47, :_reduce_14,
 1, 46, :_reduce_none,
 1, 46, :_reduce_none,
 1, 46, :_reduce_none,
 1, 46, :_reduce_none,
 1, 46, :_reduce_none,
 1, 46, :_reduce_none,
 3, 46, :_reduce_21,
 2, 46, :_reduce_22,
 3, 46, :_reduce_23,
 3, 46, :_reduce_24,
 2, 49, :_reduce_25,
 1, 49, :_reduce_26,
 2, 51, :_reduce_27,
 3, 50, :_reduce_28,
 1, 50, :_reduce_29,
 2, 53, :_reduce_30,
 2, 54, :_reduce_none,
 2, 54, :_reduce_none,
 2, 54, :_reduce_none,
 2, 54, :_reduce_none,
 2, 40, :_reduce_35,
 1, 40, :_reduce_36,
 2, 48, :_reduce_none,
 1, 48, :_reduce_none,
 1, 42, :_reduce_none,
 1, 42, :_reduce_none,
 3, 44, :_reduce_41,
 1, 44, :_reduce_42,
 2, 55, :_reduce_43,
 1, 52, :_reduce_none,
 1, 52, :_reduce_none,
 1, 52, :_reduce_none,
 1, 52, :_reduce_none,
 1, 52, :_reduce_none,
 2, 52, :_reduce_none,
 3, 52, :_reduce_none ]

racc_reduce_n = 51

racc_shift_n = 83

racc_action_table = [
     6,    76,    13,    13,    65,    45,    72,    43,    32,    33,
    32,    33,     9,    14,    17,    19,    13,    23,    13,     2,
     6,    68,    13,     7,    12,    12,    35,    37,    39,    40,
    29,    30,     9,    14,    17,    19,    13,    23,    12,     2,
    12,    32,    33,     7,    12,    71,    35,    37,    39,    40,
    29,    30,     6,    70,    13,    32,    33,    68,    12,    32,
    33,    75,    32,    33,     9,    14,    17,    19,    46,    23,
    65,     2,    32,    33,    47,     7,    12,    77,    35,    37,
    39,    40,    29,    30,     6,    10,    13,    18,    21,    32,
    33,    49,    50,     4,    79,    56,     9,    14,    17,    19,
    81,    23,    59,     2,    27,    57,   nil,     7,    12,    15,
     6,    10,    13,    18,    21,   nil,   nil,   nil,   nil,     4,
   nil,   nil,     9,    14,    17,    19,   nil,    23,   nil,     2,
    60,   nil,   nil,     7,    12,    15,     6,    10,    13,    18,
    21,   nil,   nil,   nil,   nil,     4,   nil,   nil,     9,    14,
    17,    19,   nil,    23,   nil,     2,   nil,   nil,   nil,     7,
    12,    15,     6,    10,    13,    18,    21,   nil,   nil,   nil,
   nil,     4,   nil,   nil,     9,    14,    17,    19,     6,    23,
    13,     2,   nil,   nil,   nil,     7,    12,    15,   nil,   nil,
     9,    14,    17,    19,     6,    23,    13,     2,   nil,   nil,
   nil,     7,    12,   nil,   nil,   nil,     9,    14,    17,    19,
     6,    23,    13,     2,   nil,   nil,   nil,     7,    12,   nil,
   nil,   nil,     9,    14,    17,    19,     6,    23,    13,     2,
   nil,   nil,   nil,     7,    12,   nil,   nil,   nil,     9,    14,
    17,    19,     6,    23,    13,     2,   nil,   nil,   nil,     7,
    12,   nil,   nil,   nil,     9,    14,    17,    19,    54,    23,
     6,     2,    13,   nil,   nil,     7,    12,   nil,   nil,   nil,
   nil,   nil,     9,    14,    17,    19,    74,    23,     6,     2,
    13,   nil,   nil,     7,    12,   nil,   nil,   nil,   nil,   nil,
     9,    14,    17,    19,     6,    23,    13,     2,   nil,   nil,
   nil,     7,    12,   nil,   nil,   nil,     9,    14,    17,    19,
   nil,    23,   nil,     2,   nil,   nil,   nil,     7,    12 ]

racc_action_check = [
    23,    58,    23,    15,    58,     7,    51,     7,    82,    82,
    61,    61,    23,    23,    23,    23,    43,    23,    68,    23,
    65,    48,    65,    23,    23,    15,    23,    23,    23,    23,
    23,    23,    65,    65,    65,    65,     4,    65,    43,    65,
    68,    31,    31,    65,    65,    47,    65,    65,    65,    65,
    65,    65,     3,    45,     3,    62,    62,    41,     4,    66,
    66,    56,     3,     3,     3,     3,     3,     3,    10,     3,
    34,     3,    73,    73,    11,     3,     3,    62,     3,     3,
     3,     3,     3,     3,     0,     0,     0,     0,     0,    52,
    52,    16,    18,     0,    67,    21,     0,     0,     0,     0,
    72,     0,    26,     0,     1,    22,   nil,     0,     0,     0,
    28,    28,    28,    28,    28,   nil,   nil,   nil,   nil,    28,
   nil,   nil,    28,    28,    28,    28,   nil,    28,   nil,    28,
    28,   nil,   nil,    28,    28,    28,    20,    20,    20,    20,
    20,   nil,   nil,   nil,   nil,    20,   nil,   nil,    20,    20,
    20,    20,   nil,    20,   nil,    20,   nil,   nil,   nil,    20,
    20,    20,     2,     2,     2,     2,     2,   nil,   nil,   nil,
   nil,     2,   nil,   nil,     2,     2,     2,     2,    30,     2,
    30,     2,   nil,   nil,   nil,     2,     2,     2,   nil,   nil,
    30,    30,    30,    30,    32,    30,    32,    30,   nil,   nil,
   nil,    30,    30,   nil,   nil,   nil,    32,    32,    32,    32,
    38,    32,    38,    32,   nil,   nil,   nil,    32,    32,   nil,
   nil,   nil,    38,    38,    38,    38,    29,    38,    29,    38,
   nil,   nil,   nil,    38,    38,   nil,   nil,   nil,    29,    29,
    29,    29,    19,    29,    19,    29,   nil,   nil,   nil,    29,
    29,   nil,   nil,   nil,    19,    19,    19,    19,    19,    19,
    53,    19,    53,   nil,   nil,    19,    19,   nil,   nil,   nil,
   nil,   nil,    53,    53,    53,    53,    53,    53,    79,    53,
    79,   nil,   nil,    53,    53,   nil,   nil,   nil,   nil,   nil,
    79,    79,    79,    79,    33,    79,    33,    79,   nil,   nil,
   nil,    79,    79,   nil,   nil,   nil,    33,    33,    33,    33,
   nil,    33,   nil,    33,   nil,   nil,   nil,    33,    33 ]

racc_action_pointer = [
    81,    79,   159,    49,    31,   nil,   nil,    -4,   nil,   nil,
    63,    74,   nil,   nil,   nil,    -2,    66,   nil,    89,   239,
   133,    87,    80,    -3,   nil,   nil,    77,   nil,   107,   223,
   175,    28,   191,   291,    46,   nil,   nil,   nil,   207,   nil,
   nil,    55,   nil,    11,   nil,    43,   nil,    45,    19,   nil,
   nil,     4,    76,   257,   nil,   nil,    56,   nil,   -20,   nil,
   nil,    -3,    42,   nil,   nil,    17,    46,    92,    13,   nil,
   nil,   nil,    97,    59,   nil,   nil,   nil,   nil,   nil,   275,
   nil,   nil,    -5 ]

racc_action_default = [
   -51,   -51,   -51,   -51,   -51,   -12,   -16,   -38,   -17,   -15,
   -51,   -51,   -40,   -39,   -18,   -51,   -51,   -19,   -51,   -51,
    -6,   -51,   -51,   -51,   -20,   -36,   -51,   -34,   -51,   -51,
   -51,   -44,   -51,   -51,   -30,   -45,   -29,   -46,   -51,   -47,
   -48,    -9,   -42,   -51,   -37,   -51,    -3,   -51,   -43,   -31,
    -2,    -4,   -26,   -51,   -22,   -35,   -51,   -33,   -51,   -32,
   -24,   -49,   -51,   -10,   -11,   -51,   -14,   -27,   -51,    -8,
    -7,    83,   -51,   -25,   -21,    -5,   -23,   -50,   -28,   -51,
   -41,    -1,   -13 ]

racc_goto_table = [
    31,    42,    34,    41,    20,    55,    28,    63,    64,    53,
    67,    44,    42,    55,    48,    51,    52,    78,    11,   nil,
    31,   nil,    58,   nil,   nil,   nil,    61,    62,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    66,   nil,   nil,   nil,   nil,
    69,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    73,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    31,   nil,   nil,    80,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    82 ]

racc_goto_check = [
     9,     6,    14,     8,     4,    18,     4,    10,    10,    13,
    11,     5,     6,    18,     8,     2,     9,    15,     1,   nil,
     9,   nil,    14,   nil,   nil,   nil,     9,     9,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     9,   nil,   nil,   nil,   nil,
     6,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     9,   nil,   nil,     6,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     9 ]

racc_goto_pointer = [
   nil,    18,    -3,   nil,     4,     4,    -3,   nil,    -1,    -3,
   -25,   -28,   nil,   -10,    -1,   -48,   nil,   nil,   -15,   nil ]

racc_goto_default = [
   nil,   nil,   nil,    16,   nil,   nil,    24,    26,   nil,     3,
     5,   nil,     8,   nil,   nil,    36,    38,    22,    25,     1 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 "," => 2,
 :BARENAME => 3,
 "@base" => 4,
 :EXPLICIT_URI => 5,
 "@keywords" => 6,
 "@prefix" => 7,
 :PREFIX => 8,
 "@" => 9,
 :LANGCODE => 10,
 "^^" => 11,
 "@forSome" => 12,
 "!" => 13,
 "^" => 14,
 :BOOLEAN => 15,
 :NUMERIC => 16,
 :QUICK_VARIABLE => 17,
 "(" => 18,
 ")" => 19,
 "[" => 20,
 "]" => 21,
 "{" => 22,
 "}" => 23,
 ";" => 24,
 "." => 25,
 :STRING => 26,
 :QNAME => 27,
 "@forAll" => 28,
 "<=" => 29,
 "=" => 30,
 "=>" => 31,
 "@a" => 32,
 "@has" => 33,
 "@is" => 34,
 "@of" => 35 }

racc_use_result_var = true

racc_nt_base = 36

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'","',
'BARENAME',
'"@base"',
'EXPLICIT_URI',
'"@keywords"',
'"@prefix"',
'PREFIX',
'"@"',
'LANGCODE',
'"^^"',
'"@forSome"',
'"!"',
'"^"',
'BOOLEAN',
'NUMERIC',
'QUICK_VARIABLE',
'"("',
'")"',
'"["',
'"]"',
'"{"',
'"}"',
'";"',
'"."',
'STRING',
'QNAME',
'"@forAll"',
'"<="',
'"="',
'"=>"',
'"@a"',
'"@has"',
'"@is"',
'"@of"',
'$start',
'document',
'barenames',
'declaration',
'statement_list',
'dtlang',
'symbol',
'existential',
'symbol_list',
'expression',
'path',
'objects',
'literal',
'path_list',
'property_list',
'property',
'verb',
'simple_statement',
'statement',
'universal']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

module_eval <<'.,.,', 'parser/parser.y', 3
  def _reduce_1( val, _values, result )
 val[0] << val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 4
  def _reduce_2( val, _values, result )
 return [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 6
  def _reduce_3( val, _values, result )
 return Base.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 7
  def _reduce_4( val, _values, result )
 return Keywords.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 11
  def _reduce_5( val, _values, result )
	           return Prefix.new(val[1], val[2])
   result
  end
.,.,

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

module_eval <<'.,.,', 'parser/parser.y', 17
  def _reduce_9( val, _values, result )
 return Existential.new(val[1])
   result
  end
.,.,

 # reduce 10 omitted

 # reduce 11 omitted

 # reduce 12 omitted

module_eval <<'.,.,', 'parser/parser.y', 23
  def _reduce_13( val, _values, result )
 val[0] << val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 24
  def _reduce_14( val, _values, result )
 return [val[0]]
   result
  end
.,.,

 # reduce 15 omitted

 # reduce 16 omitted

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

module_eval <<'.,.,', 'parser/parser.y', 32
  def _reduce_21( val, _values, result )
 return val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 33
  def _reduce_22( val, _values, result )
 return []
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 34
  def _reduce_23( val, _values, result )
 return Something.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 35
  def _reduce_24( val, _values, result )
 return Formulae.new(val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 37
  def _reduce_25( val, _values, result )
 val[0] << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 38
  def _reduce_26( val, _values, result )
 return [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 40
  def _reduce_27( val, _values, result )
 return Property.new(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 42
  def _reduce_28( val, _values, result )
 val[0] << val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 43
  def _reduce_29( val, _values, result )
 return [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 48
  def _reduce_30( val, _values, result )
                       return SimpleStatement.new(val[0], val[1])
   result
  end
.,.,

 # reduce 31 omitted

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

module_eval <<'.,.,', 'parser/parser.y', 54
  def _reduce_35( val, _values, result )
 val[0] << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 55
  def _reduce_36( val, _values, result )
 return [val[0]]
   result
  end
.,.,

 # reduce 37 omitted

 # reduce 38 omitted

 # reduce 39 omitted

 # reduce 40 omitted

module_eval <<'.,.,', 'parser/parser.y', 63
  def _reduce_41( val, _values, result )
 val[0] << val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 64
  def _reduce_42( val, _values, result )
 return [val[0]]
   result
  end
.,.,

module_eval <<'.,.,', 'parser/parser.y', 66
  def _reduce_43( val, _values, result )
 return Universal.new(val[1])
   result
  end
.,.,

 # reduce 44 omitted

 # reduce 45 omitted

 # reduce 46 omitted

 # reduce 47 omitted

 # reduce 48 omitted

 # reduce 49 omitted

 # reduce 50 omitted

 def _reduce_none( val, _values, result )
  result
 end

  end   # class Parser

end   # module N3
